
pumpkin_spice = {
    name = 'pumpkin_spice',
    label = 'Pumpkin Spice Elixir',
    weight = 100,
    type = 'item',
    image = 'pumpkin_spice.png',
    unique = true,
    useable = false,
    shouldClose = false,
    description = 'A magical brew said to increase your abilities temporarily',
},
golden_pumpkin = {
    name = 'golden_pumpkin',
    label = 'Golden Pumpkin',
    weight = 150,
    type = 'item',
    image = 'golden_pumpkin.png',
    unique = true,
    useable = false,
    shouldClose = false,
    description = 'A rare pumpkin imbued with good fortune. Handle with care.',
},
scary_mask = {
    name = 'scary_mask',
    label = 'Scary Mask',
    weight = 50,
    type = 'item',
    image = 'scary_mask.png',
    unique = true,
    useable = false,
    shouldClose = false,
    description = 'A creepy mask perfect for scaring others.',
},
blood_potion = {
    name = 'blood_potion',
    label = 'Blood Potion',
    weight = 80,
    type = 'item',
    image = 'blood_potion.png',
    unique = true,
    useable = true,
    shouldClose = true,
    description = 'A potion that helps restore lost health.',
},
vampire_fang = {
    name = 'vampire_fang',
    label = 'Vampire Fang',
    weight = 30,
    type = 'item',
    image = 'vampire_fang.png',
    unique = true,
    useable = false,
    shouldClose = false,
    description = 'A sharp fang from a vampire, often used in crafting.',
},
ethereal_sword = {
    name = 'ethereal_sword',
    label = 'Ethereal Sword',
    weight = 200,
    type = 'item',
    image = 'ethereal_sword.png',
    unique = true,
    useable = false,
    shouldClose = false,
    description = 'A mystical sword forged from the essence of the undead.',
},
legendary_armor = {
    name = 'legendary_armor',
    label = 'Legendary Armor',
    weight = 250,
    type = 'item',
    image = 'legendary_armor.png',
    unique = true,
    useable = false,
    shouldClose = false,
    description = 'Armor that provides protection from dark forces.',
},
dark_amulet = {
    name = 'dark_amulet',
    label = 'Dark Amulet',
    weight = 90,
    type = 'item',
    image = 'dark_amulet.png',
    unique = true,
    useable = false,
    shouldClose = false,
    description = 'An ancient amulet imbued with mysterious powers.',
},
golden_zombie = {
    name = 'golden_zombie',
    label = 'Golden Zombie Token',
    weight = 10,
    type = 'item',
    image = 'golden_zombie.png',
    unique = true,
    useable = false,
    shouldClose = false,
    description = 'A rare token representing a golden zombie.',
},
witch_brew = {
    name = 'witch_brew',
    label = 'Witch\'s Brew',
    weight = 120,
    type = 'item',
    image = 'witch_brew.png',
    unique = true,
    useable = true,
    shouldClose = true,
    description = 'A potent potion created by witches, filled with unknown powers.',
},
candy_corn = {
    name = 'candy_corn',
    label = 'Candy Corn',
    weight = 20,
    type = 'item',
    image = 'candy_corn.png',
    unique = false,
    useable = true,
    shouldClose = true,
    description = 'Sweet treats popular during Halloween, great for a quick snack.',
},
